"""
Phase 4b: Ingest approvals from HTML dashboard JSON.
Replaces CSV ingest to avoid Excel corruption issues.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from config import OUTPUT_DIR
from db import init_db, get_connection, update_approved


def run(approvals_json_path=None):
    """
    Ingest approvals from JSON file generated by HTML dashboard.
    
    Args:
        approvals_json_path: Path to review_approvals.json
    """
    if approvals_json_path is None:
        approvals_json_path = os.path.join(OUTPUT_DIR, 'review_approvals.json')
    
    if not os.path.exists(approvals_json_path):
        print(f"Error: File not found: {approvals_json_path}")
        print("Run the HTML dashboard and click 'Save Approvals' first.")
        return False
    
    init_db()
    
    # Load approvals
    with open(approvals_json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    approved_uuids = data.get('approvals', [])
    
    if not approved_uuids:
        print("No approved records found in JSON.")
        print("Open the HTML dashboard and check boxes for corrections to apply.")
        return False
    
    # Update database
    print(f"Found {len(approved_uuids)} approved records.")
    
    update_approved(approved_uuids, approved=1)
    
    # Show what will be patched
    conn = get_connection()
    cursor = conn.cursor()
    placeholders = ','.join(['?'] * len(approved_uuids))
    cursor.execute(f"""
        SELECT uuid, title_mendeley, correction_json
        FROM documents 
        WHERE uuid IN ({placeholders})
    """, approved_uuids)
    
    rows = cursor.fetchall()
    conn.close()
    
    print(f"\nApproved for patching:")
    for row in rows:
        corrections = json.loads(row['correction_json']) if row['correction_json'] else {}
        fields = list(corrections.keys()) if corrections else []
        print(f"  {row['uuid'][:12]}... - {row['title_mendeley'][:40]}...")
        if fields:
            print(f"    Fields to update: {', '.join(fields)}")
    
    print(f"\nNext step: Run python orchestrator.py patch")
    
    return True


if __name__ == "__main__":
    json_path = sys.argv[1] if len(sys.argv) > 1 else None
    success = run(json_path)
    sys.exit(0 if success else 1)
