"""Conversion Summary Slide for PDF-to-PPTX converter.

Appends a human-readable audit log slide to the end of a generated PPTX
so end-users know why and how their document was modified.

Usage:
    from summary_slide import ConversionSummary, SummarySlideBuilder, append_summary_slide

    summary = ConversionSummary(total_pages=10, total_slides=12, ...)
    append_summary_slide(prs, summary)

Standalone test:
    python summary_slide.py          # creates test_output_with_summary.pptx
"""

from __future__ import annotations

import re
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR


# ---------------------------------------------------------------------------
# Color palette
# ---------------------------------------------------------------------------

_COLOR_DARK_HEADER   = RGBColor(0x1B, 0x1F, 0x3B)  # deep navy
_COLOR_ACCENT_BLUE   = RGBColor(0x3B, 0x82, 0xF6)  # blue-500
_COLOR_ACCENT_AMBER  = RGBColor(0xF5, 0x9E, 0x0B)  # amber-500
_COLOR_ACCENT_GREEN  = RGBColor(0x10, 0xB9, 0x81)  # emerald-500
_COLOR_ACCENT_RED    = RGBColor(0xEF, 0x44, 0x44)  # red-500
_COLOR_BODY_TEXT     = RGBColor(0x1F, 0x29, 0x37)  # gray-800
_COLOR_MUTED_TEXT    = RGBColor(0x64, 0x74, 0x8B)  # slate-500
_COLOR_WHITE         = RGBColor(0xFF, 0xFF, 0xFF)
_COLOR_LIGHT_BG      = RGBColor(0xF8, 0xFA, 0xFC)  # slate-50

# SLIDE_WIDTH / SLIDE_HEIGHT for widescreen 13.33 x 7.5 in
_SLIDE_W = Inches(13.333)
_SLIDE_H = Inches(7.5)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ConversionSummary:
    """Immutable snapshot of everything the converter did to a PDF."""

    total_pages: int = 0
    total_slides: int = 0
    conversion_time_ms: float = 0.0
    phases_active: List[str] = field(default_factory=list)
    table_fallbacks: List[Dict[str, Any]] = field(default_factory=list)
    font_substitutions: List[Dict[str, Any]] = field(default_factory=list)
    collision_resolutions: List[Dict[str, Any]] = field(default_factory=list)
    spillover_events: List[Dict[str, Any]] = field(default_factory=list)
    metadata_bound: Dict[str, int] = field(default_factory=dict)
    threats_stripped: List[str] = field(default_factory=list)
    trace_id: str = ""
    pdf_name: str = ""


# ---------------------------------------------------------------------------
# Slide builder
# ---------------------------------------------------------------------------

class SummarySlideBuilder:
    """Build and append a conversion summary slide to a Presentation."""

    def __init__(self, summary: ConversionSummary):
        self.summary = summary

    # -- public API ----------------------------------------------------------

    def build_slide(self, prs: Presentation) -> None:
        """Append a summary slide to the presentation.

        Uses pptx layout index 5 (Title + Content) when available,
        falls back to index 6 (Blank) with manual text boxes.
        """
        slide_layout = self._pick_layout(prs)
        slide = prs.slides.add_slide(slide_layout)

        # Dark header background
        self._paint_header(slide)

        # Title
        self._add_title(slide, "Conversion Summary")

        # Subtitle
        self._add_subtitle(slide, "Generated by PDF-to-PPTX Converter")

        # Body content — build the full text block, then place it
        body_text = self._build_body()
        self._add_body_textbox(slide, body_text)

    # -- private helpers -----------------------------------------------------

    @staticmethod
    def _pick_layout(prs: Presentation):
        """Choose layout 5 (Title+Content) or fall back to 6 (Blank)."""
        layouts = prs.slide_layouts
        if len(layouts) > 5:
            return layouts[5]
        if len(layouts) > 6:
            return layouts[6]
        return layouts[0]

    @staticmethod
    def _paint_header(slide) -> None:
        """Fill the top ~1.6 inches with a dark rectangle."""
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = _COLOR_WHITE

        from pptx.enum.shapes import MSO_SHAPE
        rect = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Emu(0), Emu(0),
            _SLIDE_W, Inches(1.6),
        )
        rect.fill.solid()
        rect.fill.fore_color.rgb = _COLOR_DARK_HEADER
        rect.line.fill.background()
        # Send to back by manipulating XML order
        sp = rect._element
        sp.getparent().remove(sp)
        slide.shapes._spTree.insert(2, sp)

    @staticmethod
    def _add_title(slide, text: str) -> None:
        txBox = slide.shapes.add_textbox(
            Inches(0.8), Inches(0.35), Inches(11), Inches(0.65)
        )
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = _COLOR_WHITE

    @staticmethod
    def _add_subtitle(slide, text: str) -> None:
        txBox = slide.shapes.add_textbox(
            Inches(0.8), Inches(1.0), Inches(11), Inches(0.4)
        )
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(13)
        p.font.color.rgb = _COLOR_ACCENT_BLUE

    def _add_body_textbox(self, slide, body_text: str) -> None:
        txBox = slide.shapes.add_textbox(
            Inches(0.8), Inches(1.85), Inches(11.5), Inches(5.2)
        )
        tf = txBox.text_frame
        tf.word_wrap = True
        tf.auto_size = None

        lines = body_text.split("\n")
        first = True
        for line in lines:
            if first:
                p = tf.paragraphs[0]
                first = False
            else:
                p = tf.add_paragraph()

            p.space_after = Pt(2)
            p.space_before = Pt(0)

            # Section headers — detected by [brackets]
            if line.startswith("[") and "]" in line:
                p.space_before = Pt(10)
                p.space_after = Pt(3)
                run = p.add_run()
                run.text = line
                run.font.size = Pt(12)
                run.font.bold = True
                run.font.color.rgb = _COLOR_ACCENT_BLUE
            elif line.startswith("  "):
                run = p.add_run()
                run.text = line
                run.font.size = Pt(10)
                run.font.color.rgb = _COLOR_BODY_TEXT
            else:
                run = p.add_run()
                run.text = line
                run.font.size = Pt(11)
                run.font.color.rgb = _COLOR_BODY_TEXT

    def _build_body(self) -> str:
        """Assemble the full body text from all sections."""
        s = self.summary
        sections: List[str] = []

        # -- Document Info --
        doc_info = (
            f"  Source: {s.pdf_name} ({s.total_pages} pages)\n"
            f"  Output: {s.total_slides} slides\n"
            f"  Conversion time: {s.conversion_time_ms:.0f}ms\n"
            f"  Trace ID: {s.trace_id}"
        )
        sections.append("[Document Info]")
        sections.append(doc_info)

        # -- Active Features --
        if s.phases_active:
            sections.append("[Active Features]")
            for phase in s.phases_active:
                sections.append(f"  \u2022 {phase}")

        # -- Table Fallbacks --
        tbl = self._format_table_section()
        if tbl:
            sections.append(tbl)

        # -- Font Substitutions --
        fnt = self._format_font_section()
        if fnt:
            sections.append(fnt)

        # -- Collision Resolutions --
        col = self._format_collision_section()
        if col:
            sections.append(col)

        # -- Metadata Preserved --
        meta = self._format_metadata_section()
        if meta:
            sections.append(meta)

        # -- Security --
        sec = self._format_security_section()
        if sec:
            sections.append(sec)

        return "\n".join(sections)

    @staticmethod
    def _format_section(title: str, items: List[str]) -> str:
        """Format a section with title and bullet items."""
        lines = [f"[{title}]"]
        for item in items:
            lines.append(f"  \u2022 {item}")
        return "\n".join(lines)

    def _format_table_section(self) -> Optional[str]:
        fb = self.summary.table_fallbacks
        if not fb:
            return None
        pages = sorted({t.get("page", "?") for t in fb})
        page_str = ", ".join(str(p) for p in pages)
        return self._format_section(
            "Table Fallbacks",
            [f"Rejected {len(fb)} table(s) on page(s) {page_str}"],
        )

    def _format_font_section(self) -> Optional[str]:
        subs = self.summary.font_substitutions
        if not subs:
            return None
        # Group by (original, fallback) pair
        groups: Dict[tuple, List[int]] = {}
        for entry in subs:
            key = (entry.get("original", "?"), entry.get("fallback", "?"))
            groups.setdefault(key, []).append(entry.get("page", 0))
        items = []
        for (orig, fbk), pages in groups.items():
            items.append(
                f"{orig} \u2192 {fbk} on {len(pages)} page(s) "
                f"(pages {', '.join(str(p) for p in sorted(pages))})"
            )
        return self._format_section("Font Substitutions", items)

    def _format_collision_section(self) -> Optional[str]:
        cols = self.summary.collision_resolutions
        spills = self.summary.spillover_events
        if not cols and not spills:
            return None
        items = []
        if cols:
            total_pushes = sum(c.get("pushes", 0) for c in cols)
            pages = {c.get("page", "?") for c in cols}
            max_push = max((c.get("max_push_px", 0) for c in cols), default=0)
            items.append(
                f"Resolved {total_pushes} collision(s) on {len(pages)} page(s) "
                f"(max push: {max_push:.1f}pt)"
            )
        if spills:
            items.append(
                f"Spillover: {len(spills)} page(s) had elements moved to next slide"
            )
        return self._format_section("Collision Resolutions", items)

    def _format_metadata_section(self) -> Optional[str]:
        meta = self.summary.metadata_bound
        if not meta:
            return None
        parts = []
        if meta.get("hyperlinks", 0):
            parts.append(f"{meta['hyperlinks']} hyperlinks")
        if meta.get("bookmarks", 0):
            parts.append(f"{meta['bookmarks']} bookmarks")
        if meta.get("alt_texts", 0):
            parts.append(f"{meta['alt_texts']} alt-texts")
        if not parts:
            return None
        return self._format_section(
            "Metadata Preserved",
            [f"Bound {', '.join(parts)} to output slides"],
        )

    def _format_security_section(self) -> Optional[str]:
        threats = self.summary.threats_stripped
        if not threats:
            return None
        items = [f"Stripped threat: {t}" for t in threats]
        return self._format_section("Security", items)


# ---------------------------------------------------------------------------
# Integration helpers
# ---------------------------------------------------------------------------

def append_summary_slide(prs: Presentation, summary: ConversionSummary) -> bool:
    """One-call API.  Appends summary slide, returns True if slide was added."""
    try:
        builder = SummarySlideBuilder(summary)
        builder.build_slide(prs)
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Factory: ConversionResult -> ConversionSummary
# ---------------------------------------------------------------------------

_PHASE_LABELS = {
    "Theme mapper: active": "Theme Mapper",
    "Font fallback:": "Font Emulation",
    "Collisions:": "Collision Matrix",
    "Reflow:": "Reflow Grouping",
    "Metadata:": "Metadata Layer",
    "Trace:": "Telemetry",
    "Font emulation unavailable": "Font Emulation (unavailable)",
    "Metadata binding failed": "Metadata Layer (failed)",
}


def _parse_warnings(result: Any) -> Dict[str, Any]:
    """Extract structured data from the orchestrator's warning strings."""
    phases: List[str] = []
    font_subs: List[Dict[str, Any]] = []
    collision_res: List[Dict[str, Any]] = []
    spillover: List[Dict[str, Any]] = []
    metadata: Dict[str, int] = {}
    threats: List[str] = []

    for warning in getattr(result, "warnings", []):
        if not isinstance(warning, str):
            continue

        # Detect phase activation
        for prefix, label in _PHASE_LABELS.items():
            if warning.startswith(prefix):
                clean_label = label
                if "(unavailable)" in warning or "(failed)" in warning:
                    pass  # keep the label as-is with suffix
                if clean_label not in phases:
                    phases.append(clean_label)
                break

        # Font fallback count
        m = re.search(r"Font fallback:\s*(\d+)\s*clusters?\s*adjusted", warning)
        if m:
            font_subs.append({
                "page": 0,
                "original": "detected",
                "fallback": "emulated",
                "count": int(m.group(1)),
            })

        # Collision pages
        m = re.search(r"Collisions:\s*resolved on\s*(\d+)\s*pages?", warning)
        if m:
            collision_res.append({
                "page": 0,
                "pushes": int(m.group(1)),
                "max_push_px": 0.0,
            })

        # Reflow count
        m = re.search(r"Reflow:\s*(\d+)\s*shapes?\s*set to auto-fit", warning)
        if m:
            if "Reflow Grouping" not in phases:
                phases.append("Reflow Grouping")

        # Metadata — hyperlinks
        m = re.search(r"(\d+)\s*hyperlinks?\s*bound", warning)
        if m:
            metadata["hyperlinks"] = int(m.group(1))

        # Metadata — bookmarks
        m = re.search(r"(\d+)\s*bookmarks?\s*bound", warning)
        if m:
            metadata["bookmarks"] = int(m.group(1))

    return {
        "phases": phases,
        "font_subs": font_subs,
        "collision_res": collision_res,
        "spillover": spillover,
        "metadata": metadata,
        "threats": threats,
    }


def create_summary_from_result(
    result: Any,
    trace_id: str = None,
    sanitize_result: Any = None,
) -> ConversionSummary:
    """Create a ConversionSummary from an orchestrator ConversionResult.

    Extracts relevant data from the result's warnings list and other fields.
    Optionally accepts a SanitizeResult for threat information.
    """
    parsed = _parse_warnings(result)

    # Extract threats from sanitize result if available
    threats = list(getattr(sanitize_result, "threats_found", []))

    # Extract table fallback info from warnings
    table_fallbacks: List[Dict[str, Any]] = []
    for warning in getattr(result, "warnings", []):
        if isinstance(warning, str) and "table" in warning.lower() and "fallback" in warning.lower():
            table_fallbacks.append({"page": 0, "reason": warning})

    # Font substitutions — enrich with page info from warning text
    font_subs = parsed["font_subs"]
    if not font_subs:
        # Fallback: extract count from the warning
        for warning in getattr(result, "warnings", []):
            m = re.search(r"Font fallback:\s*(\d+)", str(warning))
            if m:
                font_subs.append({
                    "page": 0,
                    "original": "detected",
                    "fallback": "emulated",
                    "count": int(m.group(1)),
                })
                break

    pdf_path = getattr(result, "pdf_path", "")
    pdf_name = Path(pdf_path).name if pdf_path else "unknown.pdf"

    return ConversionSummary(
        total_pages=getattr(result, "total_pages", 0),
        total_slides=getattr(result, "total_slides", 0),
        conversion_time_ms=getattr(result, "total_time_ms", 0.0),
        phases_active=parsed["phases"],
        table_fallbacks=table_fallbacks,
        font_substitutions=font_subs,
        collision_resolutions=parsed["collision_res"],
        spillover_events=parsed["spillover"],
        metadata_bound=parsed["metadata"],
        threats_stripped=threats,
        trace_id=trace_id or str(uuid.uuid4()),
        pdf_name=pdf_name,
    )


# ---------------------------------------------------------------------------
# Standalone demo
# ---------------------------------------------------------------------------

def _demo_summary() -> ConversionSummary:
    """Build a realistic sample summary for testing."""
    return ConversionSummary(
        total_pages=24,
        total_slides=27,
        conversion_time_ms=3420.5,
        phases_active=[
            "Theme Mapper",
            "Font Emulation",
            "Collision Matrix",
            "Reflow Grouping",
            "Metadata Layer",
        ],
        table_fallbacks=[
            {"page": 3, "reason": "exceeds max rows"},
            {"page": 7, "reason": "hallucination check"},
        ],
        font_substitutions=[
            {"page": 1, "original": "HelveticaNeue-Light", "fallback": "Arial", "count": 4},
            {"page": 1, "original": "HelveticaNeue-Bold", "fallback": "Arial Bold", "count": 2},
            {"page": 5, "original": "Garamond", "fallback": "Times New Roman", "count": 1},
        ],
        collision_resolutions=[
            {"page": 2, "pushes": 3, "max_push_px": 12.4},
            {"page": 9, "pushes": 1, "max_push_px": 15.3},
        ],
        spillover_events=[
            {"page": 5, "elements_moved": 3},
        ],
        metadata_bound={"hyperlinks": 12, "bookmarks": 5},
        threats_stripped=["javascript", "xfa_form"],
        trace_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        pdf_name="quarterly_report_2025.pdf",
    )


def main() -> None:
    """Standalone test: create a PPTX with a summary slide."""
    prs = Presentation()
    prs.slide_width = _SLIDE_W
    prs.slide_height = _SLIDE_H

    summary = _demo_summary()

    ok = append_summary_slide(prs, summary)
    if not ok:
        print("ERROR: Failed to build summary slide", file=sys.stderr)
        sys.exit(1)

    out_path = Path(__file__).parent / "test_output_with_summary.pptx"
    prs.save(str(out_path))
    print(f"Created: {out_path}")
    print(f"  Slides in file: {len(prs.slides)}")
    print(f"  Summary appended: {ok}")


if __name__ == "__main__":
    main()
